export const dummyTransactions = [
  {
    date: "2024-10-01",
    category: "Food",
    paymentMode: "Debit Card",
    description: "Lunch at a restaurant",
    transactionType: "expense",
    amount: "200",
  },
  {
    date: "2024-10-02",
    category: "Transportation",
    paymentMode: "Cash",
    description: "Taxi fare",
    transactionType: "expense",
    amount: "50",
  },
  {
    date: "2024-10-03",
    category: "Rent",
    paymentMode: "Debit Card",
    description: "Monthly rent payment",
    transactionType: "expense",
    amount: "1200",
  },
  {
    date: "2024-10-04",
    category: "Salary",
    paymentMode: "Cash",
    description: "Monthly salary",
    transactionType: "income",
    amount: "5000",
  },
  {
    date: "2024-10-05",
    category: "Shopping",
    paymentMode: "Credit Card",
    description: "Clothes shopping",
    transactionType: "expense",
    amount: "300",
  },
  {
    date: "2024-10-06",
    category: "Housing",
    paymentMode: "Debit Card",
    description: "Home maintenance",
    transactionType: "expense",
    amount: "150",
  },
  {
    date: "2024-10-07",
    category: "Utilities",
    paymentMode: "Debit Card",
    description: "Electricity bill",
    transactionType: "expense",
    amount: "120",
  },
  {
    date: "2024-10-08",
    category: "Bills",
    paymentMode: "Credit Card",
    description: "Phone bill",
    transactionType: "expense",
    amount: "80",
  },
  {
    date: "2024-10-09",
    category: "Personal Care",
    paymentMode: "Cash",
    description: "Haircut",
    transactionType: "expense",
    amount: "45",
  },
  {
    date: "2024-10-10",
    category: "Extra income",
    paymentMode: "Cash",
    description: "Freelance work",
    transactionType: "income",
    amount: "350",
  },
  {
    date: "2024-10-10",
    category: "Extra income",
    paymentMode: "Cash",
    description: "Freelance work",
    transactionType: "income",
    amount: "350",
  },
];
