export const dummyTransactions = [
  {
    date: "2024-10-01",
    category: "Food",
    categoryColor: "#EF4444",
    paymentMode: "Debit Card",
    description: "Lunch at a restaurant",
    transactionType: "expense",
    amount: "200",
  },
  {
    date: "2024-10-02",
    category: "Transport",
    categoryColor: "#34D399",
    paymentMode: "Cash",
    description: "Taxi fare",
    transactionType: "expense",
    amount: "50",
  },
  {
    date: "2024-10-03",
    category: "Shopping",
    categoryColor: "#C4B5FD",
    paymentMode: "Credit Card",
    description: "Clothes shopping",
    transactionType: "expense",
    amount: "300",
  },
  {
    date: "2024-10-04",
    category: "Entertainment",
    categoryColor: "#F59E0B",
    paymentMode: "Debit Card",
    description: "Movie tickets",
    transactionType: "expense",
    amount: "100",
  },
  {
    date: "2024-10-05",
    category: "Health",
    categoryColor: "#8B5CF6",
    paymentMode: "Cash",
    description: "Pharmacy purchase",
    transactionType: "income",
    amount: "75",
  },
  {
    date: "2024-10-06",
    category: "Utilities",
    categoryColor: "#10B981",
    paymentMode: "Bank Transfer",
    description: "Electricity bill",
    transactionType: "expense",
    amount: "120",
  },
  {
    date: "2024-10-07",
    category: "Education",
    categoryColor: "#3B82F6",
    paymentMode: "Credit Card",
    description: "Online course subscription",
    transactionType: "income",
    amount: "250",
  },
  {
    date: "2024-10-08",
    category: "Travel",
    categoryColor: "#F87171",
    paymentMode: "Debit Card",
    description: "Flight tickets",
    transactionType: "expense",
    amount: "500",
  },
];
